   <html xmlns="http://www.w3.org/1999/xhtml">
    <head>	
        <title></title>

        <style type="text/css" media="all">
            @import "null?\"\{";
            @import "/css/style.css";
        </style>
   <style type="text/css">
        input.mybutton {
            background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #bdf0cd), color-stop(1, #dfdfdf) );
            background:-moz-linear-gradient( center top, #bdf0cd 5%, #dfdfdf 100% );
            filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#bdf0cd', endColorstr='#dfdfdf');
            background-color:#bdf0cd;
            -moz-border-radius:9px;
            -webkit-border-radius:9px;
            border-radius:9px;
            display:inline-block;
            color:#000000;
            font-family:Arial;
            font-size:17px;inpu
            font-weight:bold;
            padding:6px 11px;
            text-decoration:none;
        }input.mybutton:hover {
            background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #dfdfdf), color-stop(1, #bdf0cd) );
            background:-moz-linear-gradient( center top, #dfdfdf 5%, #bdf0cd 100% );
            filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#dfdfdf', endColorstr='#bdf0cd');
            background-color:#dfdfdf;
        }input.mybutton:active {
            position:relative;
            top:1px;
        }
         a.mybutton {
            background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #bdf0cd), color-stop(1, #dfdfdf) );
            background:-moz-linear-gradient( center top, #bdf0cd 5%, #dfdfdf 100% );
            filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#bdf0cd', endColorstr='#dfdfdf');
            background-color:#bdf0cd;
            -moz-border-radius:9px;
            -webkit-border-radius:9px;
            border-radius:9px;
            display:inline-block;
            color:#000000;
            font-family:Arial;
            font-size:17px;
            font-weight:bold;
            padding:6px 11px;
            text-decoration:none;
        }a.mybutton:hover {
            background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #dfdfdf), color-stop(1, #bdf0cd) );
            background:-moz-linear-gradient( center top, #dfdfdf 5%, #bdf0cd 100% );
            filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#dfdfdf', endColorstr='#bdf0cd');
            background-color:#dfdfdf;
        }a.mybutton:active {
            position:relative;
            top:1px;
        }
        /* This imageless css button was generated by CSSButtonGenerator.com */
        select{width:100px}
    </style>
    </head>
    <body>
        <div id="container">
       		<div id="masthead"><!-- BEGINNING OF LOGO AND UPPER NAVIGATION REGION: MASTHEAD -->
				<a href="http://www.ttu.edu/" id="homelink" title="Return to TTU Home" name="top"></a>
				
				<span style=" color: white;position:relative;left:90px;top:30px;">USGS Texas Cooperative Fish and Wildlife Research Unit </span><br/>
				<span style=" color: white;position:relative;left:90px;top:40px;">Texas Reservoir Water Quality Portal  </span>

			</div>
			<div id="sideBar">
				<ul><li>
				<a href="/">Welcome</a>
				</li>
				<li><a href="../../index.php/basicquery/options">Raw Data</a></li>
				<li><a href="../../index.php/welcome/userguide">Userguide</a></li>
				<li><a href="../../index.php/welcome/document">Documents</a></li>
				<li><a href="../../index.php/basicquery/desorcom">Processing/Analysis</a></li>
				</ul>
			</div>
            <div id="content">
        <?php
        $attributes = array('id' => 'form2');
        echo form_open('statistics/des_analysis', $attributes);
        ?>
        <table align="center">
            <tr><td>Descriptive Statistics:</td></tr>
            <tr><td > Statistics:Mean, Median, Max, Min, Variance</td>
                      <tr><td>Group By</td>
                <td><select name="by_time" onmousedown="if($.browser.msie){this.style.position='absolute';this.style.width='auto'}" onblur="this.style.position='';this.style.width=''">
                        <option value=1>Monthly</option>
                        <option value=2>Yearly</option>
                        <option value=3>Seasonally</option>
                    </select>
                </td>
            </tr>
                <tr>
                                        <td align="center">
                        <input type="submit" class="mybutton" value="GO">

                    </td>
                   
                </tr>

        </table>        
        <?php echo form_close() ?>
            </div>
            <div id="footer">
<script language="javascript" type="text/javascript" src="js/dates.js"></script>
<p>
<a href="mailto:jaln.liu@ttu.edu">Contact the webmaster</a><br />
	&copy;<script language="javascript" type="text/javascript">document.write(printYear());</script> <a href="http://www.ttu.edu">Texas Tech University</a> | All Rights Reserved | 
	<script language="javascript" type="text/javascript">document.write("Last Updated: " + modDate());</script>
</p>            </div>
        </div>
    </body>
   </html>
