<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title></title>
        <style type="text/css" media="all">
            @import "null?\"\{";
            @import "/css/style.css";
        </style>
    </head>
    <style type="text/css">
        input.mybutton {
            background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #bdf0cd), color-stop(1, #dfdfdf) );
            background:-moz-linear-gradient( center top, #bdf0cd 5%, #dfdfdf 100% );
            filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#bdf0cd', endColorstr='#dfdfdf');
            background-color:#bdf0cd;
            -moz-border-radius:9px;
            -webkit-border-radius:9px;
            border-radius:9px;
            display:inline-block;
            color:#000000;
            font-family:Arial;
            font-size:17px;
            font-weight:bold;
            padding:6px 11px;
            text-decoration:none;
        }input.mybutton:hover {
            background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #dfdfdf), color-stop(1, #bdf0cd) );
            background:-moz-linear-gradient( center top, #dfdfdf 5%, #bdf0cd 100% );
            filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#dfdfdf', endColorstr='#bdf0cd');
            background-color:#dfdfdf;
        }input.mybutton:active {
            position:relative;
            top:1px;
        }
        a.mybutton {
            background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #bdf0cd), color-stop(1, #dfdfdf) );
            background:-moz-linear-gradient( center top, #bdf0cd 5%, #dfdfdf 100% );
            filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#bdf0cd', endColorstr='#dfdfdf');
            background-color:#bdf0cd;
            -moz-border-radius:9px;
            -webkit-border-radius:9px;
            border-radius:9px;
            display:inline-block;
            color:#000000;
            font-family:Arial;
            font-size:17px;
            font-weight:bold;
            padding:6px 11px;
            text-decoration:none;
        }a.mybutton:hover {
            background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #dfdfdf), color-stop(1, #bdf0cd) );
            background:-moz-linear-gradient( center top, #dfdfdf 5%, #bdf0cd 100% );
            filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#dfdfdf', endColorstr='#bdf0cd');
            background-color:#dfdfdf;
        }a.mybutton:active {
            position:relative;
            top:1px;
        }
        /* This imageless css button was generated by CSSButtonGenerator.com */
        select{width:100px}
    </style>
    <body>
        <div id="container">
            <div id="masthead"><!-- BEGINNING OF LOGO AND UPPER NAVIGATION REGION: MASTHEAD -->
                <a href="http://www.ttu.edu/" id="homelink" title="Return to TTU Home" name="top"></a>

                <span style=" color: white;position:relative;left:90px;top:30px;">USGS Texas Cooperative Fish and Wildlife Research Unit </span><br/>
                <span style=" color: white;position:relative;left:90px;top:40px;">Texas Reservoir Water Data Portal  </span>

            </div>
            <div id="sideBar">
                <ul><li>
                        <a href="/">Welcome</a>
                    </li>
                    <li><a href="../../index.php/basicquery/options">Raw Data</a></li>
                    <li><a href="../../index.php/welcome/userguide">Userguide</a></li>
                    <li><a href="../../index.php/welcome/document">Documents</a></li>
                    <li><a href="../../index.php/basicquery/desorcom">Processing/Analysis</a></li>
                </ul>
            </div>
            <div id="content">
                <?php
                $attributes = array('id' => 'form2');
                echo form_open('statistics/creat_graph_des', $attributes);
                ?>
                <table align="center">
                    <tr><td>Statistics</td>
                        <td><select name="whichsta" >
                                <option value=0>Mean</option>
                                <option value=1>Median</option>	
                                <option value=2>Variance</option>
                                <option value=3>Max</option>
                                <option value=4>Min</option>
                            </select></td></tr>
                    <tr><td>Type</td>
                        <td><select name="type" >
                                <option value=1>Line</option>
                                <option value=2>Scatter</option>
                            </select></td></tr>
                    <tr><td>Title</td>
                        <td><input type="text" name="title" size="11" value="Water Quality Database Project"></tr>
 		    <tr><td>Y-axis</td>
                        <td><input type="text" name="yaxis" size="11" value="variable"></tr>

                    <tr><td>Color</td>
                        <td><select name="color">
                                <option value="blue" selected="selected">blue</option>
                                <option value="red">red</option>
                                <option value="black">black</option>
                                <option value="yellow">yellow</option>
                            </select>
                        </td>
                    </tr>
                    <tr><td>Weight</td>
                        <td><input type="text" name="weight" size="11" value="1"></td>
                    </tr>
                    <tr><td>Time Step</td>
                        <td><input type="text" name="step" size="11" value="1">
                        </td>
                    </tr>
                    <tr><td>Label Angle</td>
                        <td><input type="text" name="angle" size="11" value="30">
                        </td>
                    </tr>
                    <tr><td>Length</td>
                        <td><input type="text" name="width" size="11" value="1400">
                        </td>
                    </tr>
                    <tr><td>Width</td>
                        <td><input type="text" name="length" size="11" value="300">
                        </td>
                    </tr>
                    <tr><td align="center">
                            <input type="submit" class="mybutton" value="GO">
                        </td>
                    </tr>
                </table>

                <?php echo form_close() ?>
            </div>
            <div id="footer">
                <script language="javascript" type="text/javascript" src="js/dates.js"></script>
                <p>
                    <a href="mailto:jaln.liu@ttu.edu">Contact the webmaster</a><br />
                    &copy;<script language="javascript" type="text/javascript">document.write(printYear());</script> <a href="http://www.ttu.edu">Texas Tech University</a> | All Rights Reserved |
                    <script language="javascript" type="text/javascript">document.write("Last Updated: " + modDate());</script>
                </p>            </div>
        </div>
    </body>
</html>
